development:
    hosts:
        - "localhost"
    port: 9042
    keyspace: book_review_app_development

production:
    hosts:
        - "cassandra_host1"
        - "cassandra_host2"
    port: 9042
    keyspace: book_review_app_development
