default: &default
    hosts:
        - <%= ENV['CASSANDRA_HOST'] || 'localhost' %>
    port: 9042
    keyspace: <%= ENV['CASSANDRA_KEYSPACE'] || "book_review_app_#{Rails.env}" %>

development:
    <<: *default

test:
    <<: *default

production:
    <<: *default
