version: '3'
services:
  cassandra:
    image: cassandra:4.1.3
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    volumes:
      - .:/rails
    environment:
      - CASSANDRA_HOST=cassandra
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DISABLE_SSL=true
      - PORT=3000
    ports:
      - "3000:3000"
      
  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - web

volumes:
  cassandra_data: